### ISSUE TITLE
Move to osmus?

### ISSUE THREAD

**Issue by quincylvania** [ZeLonewolf/planetiler-scripts#16]
Now that OSM US is hosting tile generation, would it make sense to move this repo to @osmus? I'm not sure if you're using it for anything else. We could also move it to the Americana org but we'll probably end up adding a few different tile layers additional to Americana, like with the trails layer.

**Comment by ZeLonewolf** [comment]
This repo is more or less a collection of half-baked scripts, one of which I've tweaked for our OSMUS setup.  It might be better to create a clean repo under OSMUS, pull in the scripts and layer definitions we're using in production, and then we can set up full automation.

**Comment by quincylvania** [comment]
@ZeLonewolf Sounds good to me. I started a repo over at [osmus/tileservice](https://github.com/osmus/tileservice) and gave you access.

**Comment by quincylvania** [comment]
The pyrene tile renderer is now fetching the latest from [osmus/tileservice](https://github.com/osmus/tileservice) before each render and using those files to execute the run.
