### ISSUE TITLE
Add Brazilian and European Portuguese

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/planetiler-scripts#4]
This language list only includes a generic `pt` language tag for Portuguese in general, but there are some significant spelling differences between Brazilian and European Portuguese that are tagged as `name:pt-BR` and `name:pt-PT`, respectively. We should add support for these subkeys to the script:

https://github.com/ZeLonewolf/planetiler-scripts/blob/76a983c7d4b1c9f59ac713c06e26d5fc15de1f49/aws/03_render_planet.sh#L18

[The Brazilian community is discussing](https://community.openstreetmap.org/t/utilizacao-de-etiqueta-name-pt-br) which dialect(s) `name:pt` should conform to, but the choice won’t matter to OSM Americana as long as the tiles contain these regional tags, since the style will deduplicate the values intelligently (ZeLonewolf/openstreetmap-americana#670).

**Comment by quincylvania** [comment]
Done over at https://github.com/osmus/tileservice/commit/f6189f3c9728b6e559af6a8c24aa3d1362e9f6cb.
