### ISSUE TITLE
Add OpenTrailMap to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [ZeLonewolf/planetiler-scripts#8]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add OpenTrailMap to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

- URL: https://opentrailmap.us/
- Legend: https://github.com/osmus/OpenTrailMap/blob/main/README.md#legend
- Schema: https://github.com/ZeLonewolf/planetiler-scripts/blob/main/layers/osmus_trails.yml
- Source code: https://github.com/osmus/OpenTrailMap

**Comment by 1ec5** [comment]
[The YAML schema](https://github.com/ZeLonewolf/planetiler-scripts/blob/1f2440a10754445f3f147fc54ca0dc18c3030a3f/schemas/owg_simple.yml) for this tileset is already in a format very similar to what taginfo expects. A script to transform one to the other would be generally useful as part of the Planetiler project. The script could convert YAML comments into descriptions or build human-readable descriptions from the various subproperties.

**Comment by quincylvania** [comment]
This is a good idea but the tile schema offers an incomplete story. The important part is how tags are rendered and used in OpenTrailMap itself. We may not necessarily use all tags present in the tiles, and we may use additional tags fetched directly from OSM. I suggest moving this issue to https://github.com/osmus/OpenTrailMap/issues and developing a taginfo file over there.

**Comment by ZeLonewolf** [comment]
Please open a ticket in OpenTrailMap with this request.
